# Generated by Django 3.0.8 on 2020-07-24 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('classcreated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('class_day', models.CharField(max_length=200)),
                ('class_time', models.CharField(max_length=200)),
            ],
        ),
    ]
