# Generated by Django 3.0.8 on 2020-08-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Password',
            field=models.CharField(default=[], max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
