# Generated by Django 3.0.8 on 2020-08-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200801_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
