# Generated by Django 3.0.8 on 2020-08-01 18:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlequestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlequestion',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), default=[], size=None),
        ),
    ]
