# Generated by Django 3.0.8 on 2020-07-25 17:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='taken',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False], size=None),
        ),
    ]
