# Generated by Django 3.0.8 on 2020-07-24 10:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userclassrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCreator', models.BooleanField(default=False)),
                ('isOwner', models.BooleanField(default=False)),
                ('isStudent', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('beingrelated', models.DateTimeField(default=datetime.datetime.now)),
                ('myclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
